import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../',import.meta.url));
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'mk3-test-'));
fs.cpSync(path.join(root,'dist'),path.join(temp,'dist'),{recursive:true});
for(const [f,imp] of [['drag-performance.js','./vendor/three.module.js'],['collision.js','./vendor/three.module.js'],['geometry.js','./vendor/three.module.js'],['vendor/OrbitControls.js','./three.module.js'],['vendor/OBB.js','./three.module.js']]){const p=path.join(temp,'dist',f);fs.writeFileSync(p,fs.readFileSync(p,'utf8').replaceAll("'three'",JSON.stringify(imp)));}
process.on('exit',()=>fs.rmSync(temp,{recursive:true,force:true}));
class Element{constructor(tag='div'){this.tagName=tag.toUpperCase();this.style={};this.userData={};this.children=[];this.listeners={};this.options=[];this.value='';this.classList={toggle(){}};this.ownerDocument=globalThis.document;this.width=1280;this.height=800;}
 addEventListener(t,fn){(this.listeners[t]??=[]).push(fn);} removeEventListener(){} setPointerCapture(){}releasePointerCapture(){}getRootNode(){return document;}appendChild(c){this.children.push(c);return c;}replaceChildren(...c){this.children=c;this.options=c;}querySelector(){return new Element();}querySelectorAll(){return [];}getBoundingClientRect(){return{left:0,top:0,width:1280,height:800};}getContext(){return new Proxy({},{get:(t,k)=>t[k]??(()=>{}),set:(t,k,v)=>(t[k]=v,true)});}setAttribute(k,v){this[k]=v;}showModal(){this.open=true;}close(){this.open=false;}}
const els={};globalThis.document={createElement:t=>new Element(t),getElementById:id=>els[id]??(els[id]=new Element()),documentElement:{dataset:{}},addEventListener(){},removeEventListener(){}};els.segment=new Element();els.segment.options=[{},{}];els.segment.value='upper';globalThis.window={addEventListener(){},removeEventListener(){}};globalThis.innerWidth=1280;globalThis.innerHeight=800;globalThis.devicePixelRatio=1;globalThis.requestAnimationFrame=()=>{};globalThis.FakeRenderer=class{constructor(){this.domElement=new Element('canvas');this.shadowMap={};}setPixelRatio(){}setSize(){}render(){}};
els.swapVariant=new Element('select');els.swapVariant.options=[{},{}];
let s=fs.readFileSync(path.join(temp,'dist/app.js'),'utf8').replace("import * as T from 'three';","import * as ActualT from './vendor/three.module.js'; const T={...ActualT,WebGLRenderer:globalThis.FakeRenderer};");
s+='\nexport {probePose,meter,refreshProbes,refreshColliders,probeBlocked,probeObstacles,leadPath,refreshVoltageReading,animate,updatePinGuidance,highlightedPins,pinHighlightGroup,lessonMeasurement,workParts,lessonCheck,prepareLesson,swapParts,bypassPorts,align,attach,refreshCables,learning,drawMeter,updateLabels,buildScenario,parts,circuit,collision,selected,moveSelected,trySnap,rotateSelected,worldPos,worldQ,setWorldPosition,setWorldQuaternion,scene,V,Q,joints,compatible,allColliders,colliderOf,cameraSafe,camera,guardCamera,renderer,releaseDrag,drag,lastCamera,moveProbe,sceneCursor,hits,meterMode,nearbyProbeContact,updateMeterControls,turnThread,focus,connectSelected,disconnectSelected,probeTools,placeProbe,updateHitboxes,hitboxGroup,takeProbe,testStage,meterResult};\nexport function select(p){selected={port:p,part:p.part};} export function selectPart(p){selected={part:p,port:null};} export function meterOn(){meterMode="continuity";}\n';fs.writeFileSync(path.join(temp,'dist/check-app.mjs'),s);const app=await import(path.join(temp,'dist/check-app.mjs'));console.log('Runtime initialized',app.parts.length,'parts;',app.allColliders.length,'solids');globalThis.app=app;
const assert=(ok,msg)=>{if(!ok)throw new Error(msg);console.log('PASS',msg);};
// Direct placement below is fixture setup, not an alternative UI movement path.
function fixturePlaceProbe(index,contact){app.probeTools[index].contact=null;if(contact){const pose=app.probePose(contact,.18);app.probeTools[index].group.quaternion.copy(pose.quaternion);app.probeTools[index].group.position.copy(pose.position);}app.refreshProbes();app.refreshColliders();return app.placeProbe(index,contact);}
app.buildScenario('assembly');
assert(app.probeTools.length===2,'Two physical probes exist before measurement');
for(const [ai,ap,bi,bp] of [[1,0,0,0],[2,0,1,1],[2,1,3,0]]){
 const p=app.parts[ai].ports[ap],q=app.parts[bi].ports[bp];app.select(p);app.setWorldPosition(p.group,app.worldPos(q).add(app.V(0,1.5,0)));assert(!p.joint,'Approach does not auto-connect');assert(app.connectSelected(),'Button connects '+p.kind);assert(p.joint.secured,'Button secures connection');assert(!app.collision(p.group,{port:p,part:p.part}),'Connected connector clears host casing');assert(app.disconnectSelected(),'Button disconnects '+p.kind);assert(!p.joint,'Disconnected connector is free');assert(!app.collision(p.group,{port:p,part:p.part}),'Disconnect ends outside solids');}
app.buildScenario('assembly');
for(const p of app.parts.flatMap(p=>p.ports)){const entity=['screen','em'].includes(p.kind)?p.part.root:p.group;assert(!app.collision(entity,{port:p,part:p.part}),'No initial overlap '+p.kind);}
let p=app.parts[2].ports[0];app.select(p);app.setWorldPosition(p.group,app.V(5.2,1,3));app.moveSelected(app.V(5.2,1,-3));assert(app.worldPos(p).z>.2,'Fast drag cannot tunnel through EM');
assert(!app.cameraSafe(app.parts[3].root.localToWorld(app.V(0,1.2,0))),'Camera stays outside EM');
app.buildScenario('F11');app.meterOn();fixturePlaceProbe(0,{port:app.parts[1].ports[0],n:1});fixturePlaceProbe(1,{port:app.parts[1].ports[1],n:2});assert(app.meterResult==='NO PASA','Physical probes measure F11 ground');fixturePlaceProbe(0,null);assert(app.meterResult==='—','Lifting a probe clears reading');
app.buildScenario('F6');app.meterOn();fixturePlaceProbe(0,{port:app.parts[1].ports[0],n:9});fixturePlaceProbe(1,{port:app.parts[2].ports[1],n:1});assert(app.testStage.lo===1,'End-to-end failure enables segment tests');fixturePlaceProbe(1,{port:app.parts[1].ports[1],n:3});assert(app.testStage.lo===2,'Upper segment follows end-to-end');
for(const code of ['healthy','F4','F5']){app.buildScenario(code);for(const p of app.parts.flatMap(p=>p.ports)){const entity=['screen','em'].includes(p.kind)?p.part.root:p.group;assert(!app.collision(entity,{port:p,part:p.part}),'Assembled solids clear '+code+' '+p.kind);}}
console.log('Interaction checks completed.');

app.buildScenario('assembly');app.camera.updateMatrixWorld(true);app.scene.updateMatrixWorld(true);
const screenPoint=v=>v.clone().project(app.camera);
const pos=app.probeTools[0].group.localToWorld(app.V(0,0,.65)),uv=screenPoint(pos);
const event={button:0,pointerId:1,clientX:(uv.x+1)*640,clientY:(1-uv.y)*400,preventDefault(){},stopImmediatePropagation(){}};
app.renderer.domElement.listeners.pointerdown.at(-1)(event);
assert(app.drag?.probeIndex===0,'Ray-picked red handle starts physical probe drag');
const before=app.probeTools[0].group.position.clone();
app.renderer.domElement.listeners.pointermove.at(-1)({...event,clientX:event.clientX+40});
assert(before.distanceTo(app.probeTools[0].group.position)>.1,'Pointer movement moves probe');app.releaseDrag();
els.hitboxes.onclick();app.updateHitboxes();assert(app.hitboxGroup.visible&&app.hitboxGroup.children.length===app.allColliders.length,'Hitbox button draws every collider');

for(const [code,pi,porti] of [['F4',1,1],['F5',2,1]]){app.buildScenario(code);const p=app.parts[pi].ports[porti];app.select(p);assert(app.disconnectSelected(),'Button releases '+code);assert(app.connectSelected(),'Button reconnects '+code);assert(app.circuit.evaluate().screens[app.parts[0].id]==='normal','Reconnecting restores '+code);}

// Complete visible-control workflow, using the same DOM button handlers as the page.
app.buildScenario('healthy');els.modeVoltage.onclick();assert(app.meterMode==='voltage','Visible Voltage button chooses V DC');
function approachAndConnect(index,port,n){els['selectProbe'+index].onclick();const pose=app.probePose({port,n},.18);app.probeTools[index].group.quaternion.copy(pose.quaternion);app.probeTools[index].group.position.copy(pose.position);app.refreshProbes();app.refreshColliders();app.updateMeterControls();assert(!els.probeConnect.hidden,'Connect probe button appears near valid contact');assert(!app.probeTools[index].contact,'Approach alone does not attach');els.probeConnect.onclick();assert(app.probeTools[index].contact?.n===n,'Visible button connects selected probe');}

approachAndConnect(0,app.parts[3].ports[0],7);approachAndConnect(1,app.parts[3].ports[0],8);assert(app.meterResult==='12.0 V','Both connected probes produce voltage in instrument display');assert(!els.removeProbe0.disabled&&!els.removeProbe1.disabled,'Both removal buttons enabled');els.inspectMeter.onclick();assert(app.focus==='meter','View display button focuses instrument');els.modeContinuity.onclick();assert(app.meterMode==='continuity'&&app.meterResult==='NO PASA','Continuity mode updates the same contacts');els.removeProbe0.onclick();assert(!app.probeTools[0].contact&&app.meterResult==='—','Remove red clears electrical reading');els.removeProbe1.onclick();assert(!app.probeTools[1].contact&&els.removeProbe1.disabled,'Remove black frees second probe');
els.modeContinuity.onclick();approachAndConnect(0,app.parts[1].ports[0],1);approachAndConnect(1,app.parts[1].ports[1],2);assert(app.meterResult==='PASA','Repositioned probes read intact ground continuity');els.removeProbe0.onclick();els.removeProbe1.onclick();assert(app.meterResult==='—'&&app.probeTools.every(p=>!p.contact),'Complete measurement ends with both probes removed');els.modeOff.onclick();assert(app.meterMode==='off','Visible OFF button turns instrument off');

// Raycast clicks use real Three.js transforms and the actual page event handlers.
app.buildScenario('assembly');app.circuit.key=true;app.circuit.evaluate();els.modeVoltage.onclick();
const port=app.parts[1].ports[1];const norm=app.V(0,0,1).applyQuaternion(app.worldQ(port));app.camera.position.copy(app.worldPos(port).addScaledVector(norm,3));app.camera.lookAt(app.worldPos(port));app.camera.updateMatrixWorld(true);app.scene.updateMatrixWorld(true);
function clickContact(index,n){const pose=app.probePose({port,n},.34);app.probeTools[index].group.quaternion.copy(pose.quaternion);app.probeTools[index].group.position.copy(pose.position).add(app.V(0,.5,0));app.refreshProbes();app.refreshColliders();els['selectProbe'+index].onclick();const pin=port.pins.find(p=>p.userData.pin.n===n),uv=pin.getWorldPosition(app.V()).project(app.camera);const e={button:0,buttons:0,pointerId:7,clientX:(uv.x+1)*640,clientY:(1-uv.y)*400,preventDefault(){},stopImmediatePropagation(){}};const h=app.hits(e)[0];assert(h?.object.userData.pin?.n===n,'Pointer ray hits intended terminal '+n);assert(app.sceneCursor(e,h)==='crosshair'&&!els.sceneCursor.hidden,'Visible pointer changes over measurement contact');app.renderer.domElement.listeners.pointerdown.at(-1)(e);assert(!els.probeConnect.hidden,'Pointer approach exposes Connect probe');assert(!app.probeTools[index].contact,'Pointer approach waits for explicit button');els.probeConnect.onclick();assert(app.probeTools[index].contact.n===n,'Button seats pointed probe');}
clickContact(0,1);clickContact(1,2);assert(app.meterResult==='12.0 V','Complete pointer-and-button workflow reads 12.0 V');els.removeProbe0.onclick();els.removeProbe1.onclick();els.modeContinuity.onclick();clickContact(0,2);const orange=app.parts[1].ports[0],pin=orange.pins.find(p=>p.userData.pin.n===1);els.selectProbe1.onclick();app.probeTools[1].group.quaternion.copy(app.probePose({port:orange,n:1},.18).quaternion);app.probeTools[1].group.position.copy(app.probePose({port:orange,n:1},.18).position);app.updateMeterControls();els.probeConnect.onclick();assert(app.meterResult==='PASA','Same UI flow reads ground continuity');els.removeProbe0.onclick();els.removeProbe1.onclick();assert(app.meterResult==='—','UI removal ends complete measurement');assert(app.sceneCursor({clientX:100,clientY:100,buttons:0})==='default','Background restores default visible pointer');

app.buildScenario('assembly');
assert(app.allColliders.some(m=>m.userData.cableOwner),'Harness cable volumes registered');assert(app.allColliders.some(m=>m.userData.probeLead===0),'Meter lead volumes registered');assert(app.allColliders.some(m=>m.userData.probeIndex),'Probe body volumes registered');
for(const part of app.parts)for(const port of part.ports){assert(port.colliders.length===1&&port.colliders[0].userData.colliderOnly,'Continuous connector hull '+port.kind);const center=app.colliderOf(port.colliders[0]).center;assert(!app.cameraSafe(center),'Camera cannot occupy connector '+port.kind);}
for(const part of app.parts.filter(p=>['screen','em'].includes(p.type))){const inside=part.root.localToWorld(app.V(0,1.2,0));app.camera.position.copy(inside);app.lastCamera.copy(inside);app.guardCamera();assert(app.cameraSafe(app.camera.position),'Camera recovers when enclosed by '+part.type);}
app.camera.position.set(12,13,22);app.lastCamera.copy(app.camera.position);
let rigid=app.parts[2].ports[0];app.select(rigid);app.setWorldPosition(rigid.group,app.V(5.2,1,3));app.moveSelected(app.V(5.2,1,-10));assert(app.worldPos(rigid).z>.2,'Full hull stops a long sweep through EM');
app.buildScenario('assembly');app.camera.position.set(5.2,1.2,3);app.lastCamera.copy(app.camera.position);rigid=app.parts[2].ports[0];app.select(rigid);app.setWorldPosition(rigid.group,app.V(5.2,1.2,5));app.moveSelected(app.V(5.2,1.2,1));assert(app.worldPos(rigid).z>3.3,'Hardware cannot sweep over stationary camera');
app.buildScenario('assembly');app.moveProbe(0,app.V(5.2,1.2,3));app.moveProbe(0,app.V(5.2,1.2,-3));assert(app.probeTools[0].group.position.z>.2,'Probe stops against EM body');


// Complete instructional routes use the menu and Next handlers, with actual scene state.
const key=on=>{app.circuit.key=on;app.circuit.evaluate();};
const next=()=>{app.learning.tick();assert(!els.lessonNext.disabled,'Current lesson action enables Next');els.lessonNext.onclick();};
const start=id=>app.learning.start(id);
const joint=(part,port)=>{app.select(app.parts[part].ports[port]);return app.connectSelected();};
const disconnect=(part,port)=>{app.select(app.parts[part].ports[port]);assert(app.disconnectSelected(),'Disconnect physical lesson joint');};
const measure=(mode,p0,n0,p1,n1)=>{els[mode==='voltage'?'modeVoltage':'modeContinuity'].onclick();for(let i=0;i<2;i++)if(app.probeTools[i].contact)els['removeProbe'+i].onclick();approachAndConnect(0,p0,n0);approachAndConnect(1,p1,n1);};
app.learning.menu();assert(els.lessonMenuItems.children.length===8&&!els.lessonMenu.hidden,'Entry menu offers exactly eight ordered lessons');
start('assembly');assert(els.meterControls.hidden,'Assembly keeps instrument panel out of the scene');els.lessonNext.onclick();assert(app.learning.index===1,'Next advances without an action gate');els.lessonPrevious.onclick();assert(app.learning.index===0,'Previous returns without an action gate');
for(const [ai,ap,bi,bp] of [[1,0,0,0],[2,0,1,1],[2,1,3,0]]){const p=app.parts[ai].ports[ap],q=app.parts[bi].ports[bp];app.select(p);app.setWorldPosition(p.group,app.worldPos(q).add(app.V(0,1.5,0)));assert(app.connectSelected(),'Assembly lesson connects joint');next();}key(true);next();assert(!app.learning.active,'Finishing returns to menu');
start('led');key(true);assert(app.circuit.evaluate().ems[app.parts[3].id]==='blink','LED lesson normal example');next();key(true);assert(app.circuit.evaluate().ems[app.parts[3].id]==='off','LED lesson unpowered example');next();key(true);assert(app.circuit.evaluate().ems[app.parts[3].id]==='steady','LED lesson frozen example does not prematurely reboot');next();key(false);next();key(true);assert(app.circuit.evaluate().ems[app.parts[3].id]==='blink','LED example responds to OFF/ON restart');next();
start('voltage');key(true);next();measure('voltage',app.parts[3].ports[0],7,app.parts[3].ports[0],8);assert(app.meterResult==='12.0 V','Voltage lesson real 12 V');next();els.removeProbe0.onclick();els.removeProbe1.onclick();next();key(true);measure('voltage',app.parts[3].ports[0],7,app.parts[3].ports[0],8);assert(app.meterResult==='0.0 V','Voltage lesson prepares real zero-supply example');next();els.removeProbe0.onclick();els.removeProbe1.onclick();next();
start('seating');next();for(const [part,port] of [[1,0],[2,0],[2,1]]){disconnect(part,port);next();assert(joint(part,port),'Seating lesson physically reconnects');next();}key(true);next();
start('continuity');els.modeContinuity.onclick();next();measure('continuity',app.parts[1].ports[0],9,app.parts[2].ports[1],1);next();measure('continuity',app.parts[1].ports[0],10,app.parts[2].ports[1],2);next();assert(app.learning.active.steps[app.learning.index].id==='skip','Intact example ends without segment testing');els.removeProbe0.onclick();els.removeProbe1.onclick();next();measure('continuity',app.parts[1].ports[0],9,app.parts[2].ports[1],1);assert(app.meterResult==='NO PASA','Interrupted example fails end to end');next();measure('continuity',app.parts[1].ports[0],9,app.parts[1].ports[1],3);assert(app.meterResult==='PASA','Upper segment passes');next();measure('continuity',app.parts[2].ports[1],1,app.parts[2].ports[0],3);assert(app.meterResult==='NO PASA','Lower segment isolates the interruption');next();next();
for(const variant of ['screen','vehicle']){app.learning.start('swap',variant);const {suspect,good,upper,refUpper}=app.swapParts;key(true);let states=app.circuit.evaluate();assert(states.screens[suspect.id]==='spinner'&&states.screens[good.id]==='normal','Two independently powered chains before swap');next();measure('voltage',app.parts[3].ports[0],7,app.parts[3].ports[0],8);next();key(false);measure('continuity',upper.ports[0],9,app.parts[2].ports[1],1);next();measure('continuity',upper.ports[0],10,app.parts[2].ports[1],2);next();els.removeProbe0.onclick();els.removeProbe1.onclick();disconnect(1,0);disconnect(5,0);next();good.root.position.set(-5.7,0,0);suspect.root.position.set(-8,0,-5.35);app.refreshCables();next();assert(joint(1,0),'Known-good screen physically connects to problem vehicle');next();assert(joint(5,0),'Suspect screen physically connects to reference vehicle');next();key(true);states=app.circuit.evaluate();assert(states.screens[good.id]===(variant==='screen'?'normal':'spinner')&&states.screens[suspect.id]===(variant==='screen'?'spinner':'normal'),'Swap outcome '+variant+' follows actual connected hardware');next();}
start('bypass');next();app.select(app.bypassPorts[0]);assert(app.disconnectSelected(),'Bypass releases black pair');next();app.select(app.bypassPorts[2]);assert(app.disconnectSelected(),'Bypass releases striped pair');next();app.select(app.bypassPorts[0]);app.setWorldPosition(app.bypassPorts[0].group,app.worldPos(app.bypassPorts[2]).add(app.V(.5,0,0)));assert(app.connectSelected(),'Vehicle-side bypass mates');assert(app.circuit.bypassLog.length===1,'Bypass recorded separately');next();next();
start('wires');next();disconnect(1,0);assert(!app.lessonCheck('inspectOrange'),'Wire inspection waits for connector inspection');
function inspectPort(port){for(const sign of [1,-1])for(const offset of [app.V(0,.7,0),app.V(1,1,0),app.V(-1,1,0)]){const target=port.group.localToWorld(app.V(.22,.15,-.15));app.camera.position.copy(target).addScaledVector(app.V(0,0,1).applyQuaternion(app.worldQ(port)),sign*3.3).add(offset);app.camera.lookAt(target);app.camera.updateMatrixWorld(true);app.scene.updateMatrixWorld(true);const uv=target.clone().project(app.camera),event={clientX:(uv.x+1)*640,clientY:(1-uv.y)*400};let obj=app.hits(event)[0]?.object;while(obj&&!obj.userData.port)obj=obj.parent;if(obj?.userData.port!==port)continue;app.renderer.domElement.listeners.dblclick.at(-1)(event);assert(app.focus===port,'Double click inspects the requested connector');return;}throw new Error('No inspection ray for '+port.kind);}

inspectPort(app.parts[1].ports[0]);next();disconnect(2,0);inspectPort(app.parts[1].ports[1]);next();inspectPort(app.parts[2].ports[0]);next();disconnect(2,1);inspectPort(app.parts[2].ports[1]);next();app.camera.position.set(12,13,22);for(const [part,port] of [[1,0],[2,0],[2,1]])assert(joint(part,port),'Reconnect inspected conductor endpoints');next();
app.learning.menu();els.lang.onclick();assert(els.lessonMenuItems.children[0].textContent==='1. Assemble the chain','Menu translates to English');els.lang.onclick();start('voltage');app.learning.menu();start('voltage');assert(app.learning.index===0&&!app.circuit.key&&app.probeTools.every(p=>!p.contact),'Any lesson can be repeated from a clean prepared scene');
console.log('Eight-lesson menu, action gates, LED, voltage, continuity, two-way swap and bypass checks completed.');

// Traverse every lesson without hardware actions: counters, bounds, previous and repeat.
for(const lesson of (await import(path.join(temp,'dist/learning.js'))).lessons){app.learning.start(lesson.id);for(let i=0;i<lesson.steps.length;i++){app.learning.tick();assert(!els.lessonNext.disabled,'Unblocked navigation '+lesson.id+' '+(i+1));assert(els.lessonCounter.textContent===`${i+1} / ${lesson.steps.length}`,'Counter matches visible step');if(i>0){els.lessonPrevious.onclick();assert(app.learning.index===i-1,'Previous step '+lesson.id);els.lessonNext.onclick();assert(app.learning.index===i,'Forward after previous '+lesson.id);}if(i<lesson.steps.length-1)els.lessonNext.onclick();}els.lessonRestart.onclick();assert(app.learning.index===0,'Repeat returns to first step '+lesson.id);app.learning.menu();}
app.learning.start('voltage');els.lessonNext.onclick();app.updatePinGuidance();assert(app.highlightedPins.map(h=>h.n).join(',')==='7,8','Voltage step highlights pins 7 and 8');assert(app.highlightedPins.every(h=>h.ring.material.depthTest===false&&h.badge.textContent==='Pin '+h.n),'Pin rings and numbered labels remain visible above connector geometry');
const hp=app.highlightedPins[0],oldPosition=hp.ring.position.clone();hp.port.group.position.x+=.25;app.updatePinGuidance();assert(hp.ring.position.distanceTo(oldPosition)>.2,'Pin highlighting follows connector movement');
els.selectProbe0.onclick();const guidedPin=hp.port.pins.find(p=>p.userData.pin.n===7);app.probeTools[0].group.position.copy(app.probePose({port:hp.port,n:7},.18).position);app.updateMeterControls();const contact=app.nearbyProbeContact(0);assert(els.probePin0.textContent.includes('Pin '+contact.n),'Approaching probe identifies the exact candidate pin');assert(els.probeTarget.textContent.includes('pin '+contact.n),'Floating number agrees with Connect probe target');
app.learning.start('continuity');els.lessonNext.onclick();app.updatePinGuidance();assert(app.highlightedPins.map(h=>`${h.port.kind}:${h.n}`).join(',')==='orange:9,circular:1','Continuity end-to-end highlights both documented LO endpoints');els.lessonNext.onclick();app.updatePinGuidance();assert(app.highlightedPins.map(h=>h.n).join(',')==='10,2','Next step updates highlighted pins to CAN HI');els.lessonPrevious.onclick();app.updatePinGuidance();assert(app.highlightedPins.map(h=>h.n).join(',')==='9,1','Previous restores its pin highlights');app.learning.menu();app.updatePinGuidance();assert(app.highlightedPins.length===0&&els.probePin0.hidden&&els.probePin1.hidden,'Menu removes all lesson and probe pin overlays');
console.log('Unrestricted navigation for every lesson and dynamic pin guidance passed.');
app.buildScenario('healthy');app.circuit.key=true;els.modeVoltage.onclick();fixturePlaceProbe(0,{port:app.parts[3].ports[0],n:7});fixturePlaceProbe(1,{port:app.parts[3].ports[0],n:8});assert(app.meterResult==='12.0 V','Exact connected EM pins 7 and 8 read live 12 V');

// Leave the probes attached while circuit topology and key state change.
app.circuit.key=false;app.drawMeter();assert(app.meterResult==='0.0 V','Display follows key OFF without moving probes');app.circuit.key=true;app.drawMeter();assert(app.meterResult==='12.0 V','Display follows key ON without moving probes');
els.removeProbe0.onclick();els.removeProbe1.onclick();fixturePlaceProbe(0,{port:app.parts[3].ports[0],n:8});fixturePlaceProbe(1,{port:app.parts[3].ports[0],n:7});assert(app.meterResult==='-12.0 V','Real voltage polarity follows red/black contact order');els.removeProbe0.onclick();els.removeProbe1.onclick();
fixturePlaceProbe(0,{port:app.parts[3].ports[0],n:7});fixturePlaceProbe(1,{port:app.parts[3].ports[0],n:8});
app.select(app.parts[1].ports[1]);assert(app.disconnectSelected(),'Disconnect supply chain while probes remain on EM receptacle');app.animate(10000);assert(app.meterResult==='0.0 V','Animation recomputes absent EM supply from disconnected circuit');assert(app.connectSelected(),'Reconnect supply chain without lifting probes');app.animate(10100);assert(app.meterResult==='12.0 V','Animation restores voltage after actual reconnection');
app.parts[2].fault='F1';app.animate(10200);assert(app.meterResult==='0.0 V','Interrupted red conductor yields actual 0 V');app.parts[2].fault=null;app.animate(10300);assert(app.meterResult==='12.0 V','Restored red conductor yields actual 12 V');
fixturePlaceProbe(1,null);app.animate(10400);assert(app.meterResult==='—','One disconnected probe cannot retain a voltage reading');
// Teaching's deliberate zero-supply example is separate from the healthy 12 V example.
app.learning.start('voltage');els.lessonNext.onclick();app.circuit.key=true;els.modeVoltage.onclick();fixturePlaceProbe(0,{port:app.parts[3].ports[0],n:7});fixturePlaceProbe(1,{port:app.parts[3].ports[0],n:8});app.animate(10500);assert(app.meterResult==='12.0 V','Healthy voltage lesson step 2 uses actual powered graph');assert(els.meterExample.textContent.includes('sin falla'),'Healthy demonstration is labelled');els.lessonNext.onclick();els.lessonNext.onclick();app.circuit.key=true;els.modeVoltage.onclick();fixturePlaceProbe(0,{port:app.parts[3].ports[0],n:7});fixturePlaceProbe(1,{port:app.parts[3].ports[0],n:8});app.animate(10600);assert(app.meterResult==='0.0 V','Lesson step 4 remains a deliberate interrupted-supply example');assert(els.meterExample.textContent.includes('interrumpida'),'Zero-supply demonstration is explicitly labelled');
console.log('Live voltage recomputation passed for exact EM contacts, power, polarity, reconnection and conductor interruption.');

app.learning.start('continuity');assert(!els.continuityNote.hidden&&els.continuityNote.textContent.includes('polaridad no importa'),'Continuity shows persistent polarity note');els.lessonNext.onclick();assert(els.lessonBody.textContent.includes('punta negra en pin 9')&&els.lessonBody.textContent.includes('punta roja en pin 1'),'End-to-end instruction names both probe endpoints');els.lang.onclick();assert(els.continuityNote.textContent.includes('polarity does not matter')&&els.lessonBody.textContent.includes('black probe on pin 9'),'Polarity note and probe placements translate');els.lang.onclick();app.learning.start('voltage');assert(els.continuityNote.hidden,'Continuity note stays out of voltage lesson');

// Prepared middle-joint cases preserve both individual harness conductors.
for(const variant of ['middleUnsecured','middleTerminal']){
 app.learning.start('continuity',variant);assert(!els.continuityVariant.hidden&&els.continuityVariant.value===variant,'Compact selector prepares '+variant);
 const [screen,upper,lower,em]=app.workParts;
 measure('continuity',upper.ports[0],9,lower.ports[1],1);assert(app.meterResult==='NO PASA','Middle contact interrupts end-to-end CAN LO '+variant);next();
 measure('continuity',upper.ports[0],9,upper.ports[1],3);assert(app.meterResult==='PASA','Upper harness including its terminal remains continuous '+variant);next();
 measure('continuity',lower.ports[1],1,lower.ports[0],3);assert(app.meterResult==='PASA','Lower harness including its terminal remains continuous '+variant);next();
 assert(els.lessonBody.textContent.includes('contacto entre las dos mitades'),'Guide explicitly deduces failed middle contact');key(true);assert(app.circuit.evaluate().ems[em.id]==='blink'&&app.circuit.evaluate().screens[screen.id]==='spinner','Power remains normal while middle communication is interrupted '+variant);key(false);
 for(let i=0;i<2;i++)els['removeProbe'+i].onclick();disconnect(2,0);assert(joint(2,0),'Physical middle reseating '+variant);
 const state=app.circuit.evaluate();key(true);assert(app.circuit.evaluate().screens[screen.id]===(variant==='middleUnsecured'?'normal':'spinner'),'Reseating fixes securing but retains defective terminal '+variant);key(false);
 if(variant==='middleTerminal'){
 const oldContact=upper.ports[1].openContactPins;assert(oldContact.has(3),'Fault belongs to upper 4-pin pin 3');
 disconnect(1,0);disconnect(2,0);upper.root.position.set(-7,0,6.5);app.refreshCables();
 const spare=app.parts[5];for(const [port,target] of [[spare.ports[0],screen.ports[0]],[spare.ports[1],lower.ports[0]]]){app.select(port);app.setWorldPosition(port.group,app.worldPos(target).add(app.V(0,1.2,0)));assert(app.connectSelected(),'Connect known-good upper replacement to '+target.kind);}
 assert(oldContact.has(3),'Removed harness retains its defective terminal');key(true);assert(app.circuit.evaluate().screens[screen.id]==='normal','Whole upper harness replacement restores actual communication');key(false);
 measure('continuity',spare.ports[0],9,lower.ports[1],1);assert(app.meterResult==='PASA','Replacement restores end-to-end conductor');
 // Move guide to verification and ensure its highlighting follows the installed spare.
 while(app.learning.active.steps[app.learning.index].id!=='verifyLo')els.lessonNext.onclick();app.updatePinGuidance();assert(app.highlightedPins.find(h=>h.port.kind==='orange').port.part===spare,'Verification highlights installed replacement instead of removed harness');
 }
 els.lessonRestart.onclick();assert(app.learning.variant===variant&&app.learning.index===0,'Repeat preserves selected middle example');
 app.circuit.key=true;assert(app.circuit.evaluate().screens[app.workParts[0].id]==='spinner','Repeat recreates original middle contact fault');
}
els.continuityVariant.value='lowerHarness';els.continuityVariant.onchange();assert(app.learning.variant==='lowerHarness'&&app.learning.active.steps.length===8,'Selector returns to original lower-harness exercise');
console.log('Middle unsecured/contact-terminal deductions, reseating, physical replacement and repeated examples passed.');

// Regression: run the actual pointer-down / pointer-move path against every
// reported surface, including a single fast event ending beyond the obstacle.
const {segmentHitsSolid}=await import(path.join(temp,'dist/collision.js'));
for(const type of ['meter','up4','circular']){
 app.buildScenario('assembly');app.learning.menu();
 const target=type==='meter'?app.meter:app.parts[type==='up4'?1:2].ports[1].group;
 const savedPosition=target.position.clone(),savedQ=target.quaternion.clone();
 app.setWorldPosition(target,app.V(0,3,0));app.setWorldQuaternion(target,app.Q());
 const probe=app.probeTools[0].group;probe.position.set(-3,3,0);probe.quaternion.identity();
 app.camera.position.set(0,3,10);app.camera.lookAt(app.V(0,3,0));app.camera.updateMatrixWorld(true);app.refreshProbes();app.refreshColliders();app.scene.updateMatrixWorld(true);
 const project=point=>{const uv=point.project(app.camera);return{clientX:(uv.x+1)*640,clientY:(1-uv.y)*400};};
 const down={button:0,pointerId:23,preventDefault(){},stopImmediatePropagation(){},...project(probe.localToWorld(app.V(0,0,.65)))};
 app.renderer.domElement.listeners.pointerdown.at(-1)(down);assert(app.drag?.probeIndex===0,'Actual pointer picks probe for '+type);
 const from=probe.position.clone();app.renderer.domElement.listeners.pointermove.at(-1)({...down,...project(app.V(3,3,.65))});
 assert(probe.position.x>from.x+.2&&probe.position.x<-.4,'Fast pointer crossing stops on '+type);
 const targetSolids=app.allColliders.filter(m=>{for(let p=m;p;p=p.parent)if(p===target)return true;return false;});
 const probeSolids=app.allColliders.filter(m=>m.userData.probeIndex===1);
 assert(probeSolids.every(p=>targetSolids.every(t=>!app.colliderOf(p).intersectsOBB(app.colliderOf(t),1e-5))),'Stopped probe has no penetration in '+type);assert(probeSolids.some(p=>{const expanded=app.colliderOf(p).clone();expanded.halfSize.addScalar(.03);return targetSolids.some(t=>expanded.intersectsOBB(app.colliderOf(t)));}),'Probe stops within one sweep increment of the requested surface '+type);
 const stopped=probe.position.clone();app.renderer.domElement.listeners.pointermove.at(-1)({...down,...project(app.V(8,3,.65))});assert(probe.position.distanceTo(stopped)<.026,'Continued pressure cannot cross '+type);app.releaseDrag();
 // The rendered lead's centerline, widened by its radius, stays outside each rigid solid.
 const boxes=app.probeObstacles(0).map(o=>o.obb),points=app.probeTools[0].leadPoints;
 assert(points&&points.slice(1).every((p,i)=>boxes.every(o=>!segmentHitsSolid(points[i],p,o,.038))),'Lead remains outside solid surfaces for '+type);
 target.position.copy(savedPosition);target.quaternion.copy(savedQ);
}
// A probe must also stop against an actual harness cable, not just rigid pieces.
app.buildScenario('assembly');const cableSolid=app.allColliders.find(m=>m.userData.cableOwner===app.parts[1]),cableBox=app.colliderOf(cableSolid),probe=app.probeTools[0].group;
probe.quaternion.identity();probe.position.copy(cableBox.center).add(app.V(0,1.5,-.6));app.refreshProbes();app.refreshColliders();app.moveProbe(0,cableBox.center.clone().add(app.V(0,-1.5,-.6)));
assert(probe.position.y>cableBox.center.y,'Probe sweep stops at harness cable');
console.log('Actual pointer crossing attempts stopped on meter, 4-pin and circular shells; lead clearance and harness contact passed.');
